# Generated by Django 4.2.4 on 2023-09-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the publisher", max_length=50),
                ),
                ("website", models.URLField(help_text="Publisher's website")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Publisher's email address"
                    ),
                ),
            ],
        ),
    ]
